# Generated by Django 4.2.7 on 2024-02-26 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=16)),
                ('lname', models.CharField(max_length=11)),
                ('username', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='per_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FatherName', models.CharField(max_length=16)),
                ('MartialStatus', models.CharField(max_length=17)),
                ('Edu_Qua', models.CharField(max_length=12)),
                ('YearOfPassing', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='post_salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Designation', models.CharField(max_length=20)),
                ('salary', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='profo_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cur_Company', models.CharField(max_length=17)),
                ('Reliving_Date', models.DateField()),
                ('New_Company', models.CharField(max_length=15)),
                ('Experience', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='regform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MobileNumber', models.IntegerField()),
                ('DateOfBirth', models.DateField()),
                ('Age', models.IntegerField()),
                ('Gender', models.CharField(max_length=10)),
                ('EmailID', models.EmailField(max_length=21)),
                ('KnownLang', models.CharField(max_length=18)),
                ('Country', models.CharField(max_length=20)),
                ('Address', models.CharField(max_length=45)),
            ],
        ),
    ]
