# Generated by Django 4.2.7 on 2024-02-29 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='expec_salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Designation', models.CharField(max_length=20)),
                ('expect_salary', models.IntegerField(null=True)),
            ],
        ),
    ]
