# Generated by Django 4.2.7 on 2024-03-06 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_expec_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=20)),
                ('Professional', models.CharField(max_length=20)),
                ('Gender', models.CharField(max_length=20)),
                ('DateOfBirth', models.DateField()),
                ('MobileNumber', models.IntegerField()),
                ('EmailID', models.EmailField(max_length=21)),
                ('Country', models.CharField(max_length=20)),
                ('State', models.CharField(max_length=25)),
                ('District', models.CharField(max_length=30)),
                ('Location', models.CharField(max_length=20)),
            ],
        ),
    ]
