# Generated by Django 4.2.7 on 2024-03-06 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='MobileNumber',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='State',
            field=models.CharField(max_length=30),
        ),
    ]
