# Generated by Django 4.2.7 on 2024-03-08 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_alter_information_mobilenumber_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=16)),
                ('lname', models.CharField(max_length=16)),
                ('DateOfBirth', models.DateField()),
                ('Age', models.IntegerField(null=True)),
                ('Sex', models.CharField(max_length=20)),
                ('KnownLang', models.CharField(max_length=16)),
                ('EmailId', models.CharField(max_length=16)),
                ('EmailId_1', models.CharField(max_length=16)),
                ('pass_1', models.CharField(max_length=16)),
                ('pass_2', models.CharField(max_length=16)),
            ],
        ),
    ]
