# Generated by Django 4.2.7 on 2024-03-08 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_signup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='Sex',
            new_name='Gender',
        ),
    ]
