# Generated by Django 4.2.7 on 2024-03-12 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0007_alter_signup_emailid_alter_signup_emailid_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='EmailId_1',
            field=models.CharField(max_length=16),
        ),
    ]
